steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}'
      - '--build-arg'
      - 'VITE_API_BASE=${_VITE_API_BASE}'
      - '.'
images:
  - '${_IMAGE_NAME}'
substitutions:
  _IMAGE_NAME: 'placeholder'
  _VITE_API_BASE: ''
